//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropoPlot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string AvgPrd {
            get {
                return ((string)(this["AvgPrd"]));
            }
            set {
                this["AvgPrd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-9.0")]
        public string FALatMin {
            get {
                return ((string)(this["FALatMin"]));
            }
            set {
                this["FALatMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90.0")]
        public string FALatMax {
            get {
                return ((string)(this["FALatMax"]));
            }
            set {
                this["FALatMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string FALongMin {
            get {
                return ((string)(this["FALongMin"]));
            }
            set {
                this["FALongMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144")]
        public string FALongMax {
            get {
                return ((string)(this["FALongMax"]));
            }
            set {
                this["FALongMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string EULatMin {
            get {
                return ((string)(this["EULatMin"]));
            }
            set {
                this["EULatMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
        public string EULatMax {
            get {
                return ((string)(this["EULatMax"]));
            }
            set {
                this["EULatMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-12")]
        public string EULongMin {
            get {
                return ((string)(this["EULongMin"]));
            }
            set {
                this["EULongMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string EULongMax {
            get {
                return ((string)(this["EULongMax"]));
            }
            set {
                this["EULongMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string JALatMin {
            get {
                return ((string)(this["JALatMin"]));
            }
            set {
                this["JALatMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46")]
        public string JALatMax {
            get {
                return ((string)(this["JALatMax"]));
            }
            set {
                this["JALatMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public string JALongMin {
            get {
                return ((string)(this["JALongMin"]));
            }
            set {
                this["JALongMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("145")]
        public string JALongMax {
            get {
                return ((string)(this["JALongMax"]));
            }
            set {
                this["JALongMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string NALatMin {
            get {
                return ((string)(this["NALatMin"]));
            }
            set {
                this["NALatMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public string NALatMax {
            get {
                return ((string)(this["NALatMax"]));
            }
            set {
                this["NALatMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-131")]
        public string NALongMin {
            get {
                return ((string)(this["NALongMin"]));
            }
            set {
                this["NALongMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-54")]
        public string NALongMax {
            get {
                return ((string)(this["NALongMax"]));
            }
            set {
                this["NALongMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-60")]
        public string SALatMin {
            get {
                return ((string)(this["SALatMin"]));
            }
            set {
                this["SALatMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string SALatMax {
            get {
                return ((string)(this["SALatMax"]));
            }
            set {
                this["SALatMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-90")]
        public string SALongMin {
            get {
                return ((string)(this["SALongMin"]));
            }
            set {
                this["SALongMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32")]
        public string SALongMax {
            get {
                return ((string)(this["SALongMax"]));
            }
            set {
                this["SALongMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-54")]
        public string OCLatMin {
            get {
                return ((string)(this["OCLatMin"]));
            }
            set {
                this["OCLatMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public string OCLatMax {
            get {
                return ((string)(this["OCLatMax"]));
            }
            set {
                this["OCLatMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112")]
        public string OCLongMin {
            get {
                return ((string)(this["OCLongMin"]));
            }
            set {
                this["OCLongMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("126")]
        public string OCLongMax {
            get {
                return ((string)(this["OCLongMax"]));
            }
            set {
                this["OCLongMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-35")]
        public string AFLatMin {
            get {
                return ((string)(this["AFLatMin"]));
            }
            set {
                this["AFLatMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34")]
        public string AFLatMax {
            get {
                return ((string)(this["AFLatMax"]));
            }
            set {
                this["AFLatMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-20")]
        public string AFLongMin {
            get {
                return ((string)(this["AFLongMin"]));
            }
            set {
                this["AFLongMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string AFLongMax {
            get {
                return ((string)(this["AFLongMax"]));
            }
            set {
                this["AFLongMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string PeriodTimer {
            get {
                return ((string)(this["PeriodTimer"]));
            }
            set {
                this["PeriodTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string EUAvgColor {
            get {
                return ((string)(this["EUAvgColor"]));
            }
            set {
                this["EUAvgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string EURawColor {
            get {
                return ((string)(this["EURawColor"]));
            }
            set {
                this["EURawColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string EUCntColor {
            get {
                return ((string)(this["EUCntColor"]));
            }
            set {
                this["EUCntColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string JAAvgColor {
            get {
                return ((string)(this["JAAvgColor"]));
            }
            set {
                this["JAAvgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string JARawColor {
            get {
                return ((string)(this["JARawColor"]));
            }
            set {
                this["JARawColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string JACntColor {
            get {
                return ((string)(this["JACntColor"]));
            }
            set {
                this["JACntColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string NAAvgColor {
            get {
                return ((string)(this["NAAvgColor"]));
            }
            set {
                this["NAAvgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string NARawColor {
            get {
                return ((string)(this["NARawColor"]));
            }
            set {
                this["NARawColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string NACntColor {
            get {
                return ((string)(this["NACntColor"]));
            }
            set {
                this["NACntColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string OCAvgColor {
            get {
                return ((string)(this["OCAvgColor"]));
            }
            set {
                this["OCAvgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string OCRawColor {
            get {
                return ((string)(this["OCRawColor"]));
            }
            set {
                this["OCRawColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string OCCntColor {
            get {
                return ((string)(this["OCCntColor"]));
            }
            set {
                this["OCCntColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string AFAvgColor {
            get {
                return ((string)(this["AFAvgColor"]));
            }
            set {
                this["AFAvgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string AFRawColor {
            get {
                return ((string)(this["AFRawColor"]));
            }
            set {
                this["AFRawColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string AFCntColor {
            get {
                return ((string)(this["AFCntColor"]));
            }
            set {
                this["AFCntColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string SACntColor {
            get {
                return ((string)(this["SACntColor"]));
            }
            set {
                this["SACntColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string SARawColor {
            get {
                return ((string)(this["SARawColor"]));
            }
            set {
                this["SARawColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string SAAvgColor {
            get {
                return ((string)(this["SAAvgColor"]));
            }
            set {
                this["SAAvgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string FAAvgColor {
            get {
                return ((string)(this["FAAvgColor"]));
            }
            set {
                this["FAAvgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string FARawColor {
            get {
                return ((string)(this["FARawColor"]));
            }
            set {
                this["FARawColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008B8B")]
        public string FACntColor {
            get {
                return ((string)(this["FACntColor"]));
            }
            set {
                this["FACntColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string AvgLineThick {
            get {
                return ((string)(this["AvgLineThick"]));
            }
            set {
                this["AvgLineThick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string RawLineThick {
            get {
                return ((string)(this["RawLineThick"]));
            }
            set {
                this["RawLineThick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string CntLineThick {
            get {
                return ((string)(this["CntLineThick"]));
            }
            set {
                this["CntLineThick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string GraphAvgDotSize {
            get {
                return ((string)(this["GraphAvgDotSize"]));
            }
            set {
                this["GraphAvgDotSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string GraphRawDotSize {
            get {
                return ((string)(this["GraphRawDotSize"]));
            }
            set {
                this["GraphRawDotSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string GraphCntDotSize {
            get {
                return ((string)(this["GraphCntDotSize"]));
            }
            set {
                this["GraphCntDotSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Avg2LineThick {
            get {
                return ((string)(this["Avg2LineThick"]));
            }
            set {
                this["Avg2LineThick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usr")]
        public string UsrDefinedName {
            get {
                return ((string)(this["UsrDefinedName"]));
            }
            set {
                this["UsrDefinedName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.11")]
        public string txtPan {
            get {
                return ((string)(this["txtPan"]));
            }
            set {
                this["txtPan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public string goTryLine {
            get {
                return ((string)(this["goTryLine"]));
            }
            set {
                this["goTryLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string yourCall {
            get {
                return ((string)(this["yourCall"]));
            }
            set {
                this["yourCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string theirCall {
            get {
                return ((string)(this["theirCall"]));
            }
            set {
                this["theirCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkHiLiteDX {
            get {
                return ((bool)(this["chkHiLiteDX"]));
            }
            set {
                this["chkHiLiteDX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70000")]
        public string truncateValue {
            get {
                return ((string)(this["truncateValue"]));
            }
            set {
                this["truncateValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string myFontSize {
            get {
                return ((string)(this["myFontSize"]));
            }
            set {
                this["myFontSize"] = value;
            }
        }
    }
}
